### ISSUE TITLE
stack

### ISSUE THREAD

**Issue by Maxopoly** [Civcraft/AttrHider#7]
[23:58:36 ERROR]: [AttrHider] Unhandled exception occured in onPacketSending(PacketEvent) for AttrHider
java.lang.IllegalArgumentException: Multiple entries with same key: Enchantment[34, DURABILITY]=3 and Enchantment[34, DURABILITY]=2
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(RegularImmutableMap.java:104) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at com.google.common.collect.RegularImmutableMap.<init>(RegularImmutableMap.java:70) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:254) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.getEnchantments(CraftItemStack.java:305) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at org.bukkit.craftbukkit.v1_9_R1.inventory.CraftItemStack.getEnchantments(CraftItemStack.java:286) ~[spigot.jar:git-Spigot-e000104-4cb3258]
        at com.civpvp.attrhider.AttrHider$1.onPacketSending(AttrHider.java:63) ~[AttrHider-1.1.1.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:608) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:584) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:309) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:269) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:396) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:362) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:330) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.0.0-SNAPSHOT-b275]
        at net.minecraft.server.v1_9_R1.NetworkManager.a(NetworkManager.java:193) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.NetworkManager.sendPacket(NetworkManager.java:142) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.PlayerConnection.sendPacket(PlayerConnection.java:1096) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:292) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.EntityTracker.a(EntityTracker.java:223) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.EntityLiving.m(EntityLiving.java:1741) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.EntityInsentient.m(EntityInsentient.java:244) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.EntityMonster.m(EntityMonster.java:28) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.World.entityJoinedWorld(World.java:1650) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.World.g(World.java:1625) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.World.tickEntities(World.java:1434) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.WorldServer.tickEntities(WorldServer.java:630) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:792) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
[23:58:36 ERROR]: Parameters:
  net.minecraft.server.v1_9_R1.PacketPlayOutEntityEquipment@4a3be9c1[
    a=18859
    b=HEAD
    c=1xitem.helmetGold@20
  ]

**Comment by ProgrammerDan** [comment]
Well that's exciting. Why would it have durability 2 and 3? fancy.

**Comment by tyrothalos** [comment]
Is this still a problem?

**Comment by Maxopoly** [comment]
No
